(in-package :common-lisp-user)

(defpackage :nautowrite
  (:use :common-lisp :general :names :object :symbols :terms)
  (:export
   #:constant-symbol
   #:make-constant-symbol
   #:signed-object
   #:*spec*
   #:*specs*
   #:table-automaton
   #:automaton
   #:tautomaton
   #:automata
   #:tautomata
   #:trs
   #:trss
   #:termset
   #:termsets
   #:term
   #:term-size
   #:term-depth
   #:term-nb-leaves
   #:*new-var-ter*
   #:terms
   #:previous-term
   #:get-automaton
   #:get-termset
   #:show
   #:set-current-automaton
   #:set-current-tautomaton
   #:add-automaton-to-tautomaton
   #:remove-automaton
   #:remove-tautomaton
   #:set-current-trs
   #:set-current-term
   #:set-current-termset
   #:set-current-spec
   #:build-spec
   #:build-termset
   #:*extra-symbol*
   #:redex-positions
   #:seqsys-merge-signature
   #:signature-from
   #:needed-redex-positions
   #:in-signature
   #:in-signature-bullet
   #:in-signature-extra
   #:outer-positions
   #:parallel-reduction-step
   #:reduction-step
   #:contains-bullet-p
   #:display-sequential
   #:display-sequentiality-results
   #:seqsys-aut-c
   #:seqsys-aut-c-t
   #:seqsys-change-aut-t
   #:seqsys-aut-d
   #:seqsys-aut-d-extra
   #:try-to-check-seq-with-properties
   #:compare-object
   #:find-object
   #:constructor
   #:constructor-p
   #:forward-branching-index-tree
   #:get-rules
   #:make-rules
   #:name
   #:outermost-redex-positions
   #:salinier
   #:seqsys-normal-form
   #:*data-directory*
   #:initial-data-directory
   #:with-left-linearity
   #:approx-arbitrary
   #:wn-inclusion
   #:normalizable
   #:term-needed-redexes
   #:accessibility
   #:growing-terminating
   #:inverse-growing-terminating
   #:nf-empty
   #:enf-empty
   #:signature-empty-p
   #:get-approx-rules
   #:get-rules
   #:nb-symbols
   #:seqsys-approx
   #:signature
   #:signature-symbols
   #:signature-difference
   #:*jacquemard*
   #:ground
   #:left-linear
   #:init-autowrite
   #:normalize-string
   #:list-values
   #:list-keys
   #:table
   #:*limit-transitions*
   #:toggle-limit-transitions
   #:aut-termset
   #:vars
   #:write-object-to-file
   #:display-sequence
   #:absolute-filename
   #:get-lhs
   #:get-spec
   #:get-terms
   #:transitions-of
   #:make-name
   #:write-name
   #:compose-name
   #:update-approximation
   #:compute-state
   #:compute-target
   #:tcompute-target
   #:tcompute-state
   #:growing
   #:included-signature-p
   #:deterministic-p
   #:complete-p
   #:automaton-empty
   #:duplicate-automaton
   #:nskim-automaton
   #:epsilon-closure-automaton
   #:equality-automaton
   #:union-automaton
   #:disjoint-union-automaton
   #:inclusion-automaton
   #:determinize-automaton
   #:reduce-automaton
   #:complete-automaton
   #:complement-automaton
   #:minimize-automaton
   #:simplify-automaton
   ;;	   #:ndeterminize-automaton
   #:nreduce-automaton
   #:ncomplete-automaton
   #:ncomplement-automaton
   #:nminimize-automaton
   #:intersection-automaton
   #:intersection-emptiness
   #:automaton-emptiness
   #:minimal-p
   #:simplified-p
   #:name-states
   #:number-states
   #:show-automaton-characteristics
   #:show-tautomaton-characteristics
   ;; trss operations
   #:inverse-rules
   #:inverse-seqsys
   #:left-handside
   #:right-handside
   #:linear-terms-p
   #:load-aut-spec
   #:make-redex-automaton
   #:make-reducible-automaton
   #:positions-to-string
   #:read-automaton
   #:read-rules
   #:read-spec-from-path
   #:read-termset
   #:recognized-p
   #:reduced-p
   #:reduced-automaton-p
   #:rename-object
   #:rule
   #:rules
   #:rules-list
   #:save-spec
   #:seqsys-aut-nf
   #:seqsys-aut-nf-bullet
   #:seqsys-from-rules
   #:term-check-property
   #:trs-check-collapsing
   #:trs-check-constructor
   #:trs-check-forward-branching
   #:trs-check-growing
   #:trs-check-orthogonal
   #:trs-check-overlapping
   #:trs-check-property
   #:trs-check-forward-branching
   #:size
   #:*loadable*
   #:load-tautomaton
   #:load-file-from-absolute-filename
   #:load-trs-spec
   #:read-term
   #:growing-approximation
   #:linear-growing-approximation
   #:strong-approximation
   #:nv-approximation
   #:*output-stream*
   #:avec-temps
   #:evaluate-time
   #:avec-temps-to-output-stream
   #:var-p
   #:union-automata
   #:intersection-automata
   #:equivalence-classes
   #:equivalence-classes-automaton
   #:final-state-p
   #:puits-state-p
   #:state-final-p
   #:state-puits-p
   #:state-success-p
   #:strictly-ordered-state-p
   #:ok-state
   #:puits-state
   #:ok-ok-state
   #:*ok-ok-state*
   #:neutral-state
   #:final-neutral-state
   #:casted-state
   #:cast-automaton
   #:abstract-state
   #:*empty-symbol*
   #:parity-symbol
   #:vbits-constant-symbol
   #:abstract-automaton
   #:fly-automaton
   #:make-fly-automaton
   #:states-table
   #:reset-states-table
   #:states-from-states-table
   #:to-fly-automaton
   #:compile-automaton
   #:flatten
   #:*neutral-state-final-p*
   #:*neutral-state*
   #:*final-neutral-state*
   #:*ok-state*
   #:vbits
   #:color-constant-symbol
   #:color-constant-symbol-p
   #:iota
   #:cartesian-product
   #:distribute-set
   #:arrange
   #:make-vbits-constant-symbol
   #:make-zero-vbits-constant-symbol
   #:make-random-partition-vbits-constant-symbol
   #:make-random-vbits-constant-symbol
   #:make-parity-symbol
   #:*commutative-symbols*
   #:make-commutative-bin-symbol
   #:make-signature
   #:input-term
   #:vprojection
   #:vprojection-automaton
   #:build-term
   #:remove-duplicates-except-pairs
   #:adjoin-sort
   #:adjoin-symbol-to-signature
   #:arg
   #:symbol-color
   #:constant
   #:constant-signature
   #:container-remove-if-not
   #:container-size
   #:cprojection
   #:cprojection-automaton
   #:difference-sort
   #:fill-spec
   #:get-states
   #:get-finalstates
   #:get-tautomaton
   #:hvmodification
   #:intersection-automaton-compatible
   #:intersection-automaton-compatible-gen
   #:intersection-sort
   #:leaves-of-term
   #:lexically-strictly-ordered-p
   #:make-color-constant-symbol
   #:make-tautomaton
   #:make-vbits
   #:member-sort
   #:my-remove-duplicates
   #:new-omult-target
   #:nsimplify-automaton
   #:number-of-transitions
   #:numbers-to-name
   #:op-automata-list
   #:order-state
   #:powerset
   #:root
   #:test-automata
   #:test-call-by-need
   #:union-sort
   #:vcylindrification
   #:verify-automaton
   #:vhomomorphism
   #:vhomomorphism-with-empty-symbol
   #:*GLOBAL-TRANSITIONS*
   #:spec
   #:non-emptiness-witness
   #:x1-to-nothing
   #:x1-to-xj
   #:x1-to-color
   #:x1-to-bool-x1
   #:x1-to-bool-xi
   #:xj-to-cxj
   #:x1-to-cx1
   #:xi-to-cxj
   #:nothing-to-random
   #:nothing-to-random-color
   #:nothing-to-random-partition
   #:nothing-to-x1
   #:nothing-to-xj
   #:nothing-to-color
   #:nothing-to-xj1-union-xj2
   #:nothing-to-xj1-intersection-xj2
   #:nothing-to-c1-union-c2
   #:x1-to-xj1-union-xj2
   #:x1-to-xj1-intersection-xj2
   #:y1-y2-to-xj1-xj2
   #:y1-y2-to-xj-xj1-union-xj2
   #:y1-y2-to-xj-xj1-intersection-xj2
   #:lvbits
   #:add-empty-symbol
   #:term-randomize-vbits
   #:casted-p
   #:rename-and-save
   #:annotation
   #:compute-annotation
   #:erase-annotation
   #:remove-annotation
   #:annotated-parity-symbol
   #:annotated-commutative-symbol
   #:sym
   #:abstract-arity-symbol
   #:abstract-parity-symbol
   #:run
   #:erase-run
   #:*cast*
   #:state-size
   #:hash-reduce
   #:biggest-state
   #:*clean-states-table*
   #:*max-number-of-states*
   #:state
   ))
