(in-package :common-lisp-user)

(defpackage :symbols
  (:use :common-lisp :general :names :object)
  (:export
   #:init-symbols
   #:*print-arity*
   #:*commutative-symbols*
   #:arity
   #:symbol-member
   #:symbol-remove
   #:symbol-adjoin
   #:symbol-delete
   #:symbols-from
   #:constant-symbol
   #:vbits-constant-symbol
   #:vbits-constant-symbol
   #:make-random-partition-vbits-constant-symbol
   #:make-random-vbits-constant-symbol
   #:make-random-color-constant-symbol
   #:make-zero-vbits-constant-symbol
   #:color-constant-symbol
   #:color-constant-symbol-p
   #:symbol-color
   #:abstract-symbol
   #:abstract-arity-symbol
   #:abstract-parity-symbol
   #:arity-symbol
   #:parity-symbol
   #:commutative-symbol
   #:commutative-symbol-mixin
   #:constant-symbol-p
   #:commutative-symbol-p
   #:unranked-symbol-p
   #:unranked-symbol
   #:arity-symbolp
   #:find-symbol-from-name
   #:find-constant-symbol-with-vbits
   #:vbits
   #:make-vbits
   #:make-constant-symbol
   #:make-vbits-constant-symbol
   #:make-color-constant-symbol
   #:make-commutative-symbol
   #:make-commutative-bin-symbol
   #:make-arity-symbol
   #:make-parity-symbol
   #:make-unranked-symbol
   #:make-annotated-parity-symbol
   #:symbol-isconstant
   #:symbol-subsetp
   #:symbol-intersection
   #:symbol-union
   #:symbol-remove-duplicates
   #:symbol-delete-duplicates
   #:symbol-set-difference
   #:symbols-from
   #:reset-aux-symbols
   #:make-aux-symbol
   #:signature
   #:signature-from
   #:get-arities
   #:max-arity
   #:arrange-signature
   #:constant-signature
   #:non-constant-signature
   #:merge-signature
   #:copy-signature
   #:nb-symbols
   #:included-signature-p
   #:homogeneous-constant-signatures-p
   #:equiv-signature-p
   #:adjoin-symbol-to-signature
   #:remove-symbol-from-signature
   #:remove-symbols-from-signature
   #:add-bullet-symbol
   #:add-empty-symbol
   #:add-extra-symbol
   #:remove-bullet-symbol
   #:remove-extra-symbol
   #:signature-intersection
   #:signature-union
   #:signature-difference
   #:signature-empty-p
   #:signature-symbols
   #:signature-arities
   #:symbols-of-arity
   #:make-signature
   #:in-signature
   #:in-signature-extra
   #:in-signature-bullet
   #:*bullet-symbol*
   #:*extra-symbol*
   #:*omega-symbol*
   #:*empty-symbol*
   #:empty-symbol
   #:*predefined-symbols*
   #:signed-object
   #:signature-mixin
   #:signature
   #:*signature-mapping*
   #:all-symbols
   #:aux-symbols
   #:symbol-to-annotated-symbol
   #:annotated-arity-symbol
   #:annotated-parity-symbol
   #:sym
   ))
