(in-package :common-lisp-user)

(defpackage :terms
  (:use :common-lisp :general :object :symbols :names)
  (:export
   #:reset-aux-variables
   #:init-variables
   #:var
   #:var-p
   #:find-var-from-name
   #:make-var
   #:variable-member
   #:variable-delete-duplicates
   #:variable-delete
   #:make-aux-var
   #:aux-var-p
   #:make-binding
   #:g-gen-substitution
   #:*aux-variables*
   #:vars-of
   #:my-position
   #:make-position
   #:extend-position
   #:outer-positions
   #:position-to-string
   #:positions-to-string
   #:term
   #:abstract-term
   #:arg
   #:root
   #:build-term
   #:bullet-term
   #:extra-term
   #:omega-term
   #:*new-var*
   #:init-terms
   #:term-p
   #:constant
   #:zeroary
   #:linearize
   #:rename-vars
   #:subterms
   #:subterms-list
   #:strict-subterms
   #:strict-subterms-list
   #:linearize-existing
   #:linear
   #:linear-terms-p
   #:ground
   #:my-copy-term
   #:contains-bullet-p
   #:constructor-symbols-p
   #:build-zeroary-terms-from-symbols
   #:bullet-bindings
   #:substitute-bullet
   #:apply-substitution
   #:omega-term-p
   #:omega-positions
   #:term-at-position
   #:term-paths
   #:term-positions
   #:term-at-path
   #:term-at-position
   #:replace-term-at-path
   #:replace-term-at-position
   #:nreplace-term-at-path
   #:residual-paths
   #:replace-terms-at-positions
   #:non-omega-positions
   #:omega-positions-list
   #:non-omega-positions-list
   #:le
   #:lt
   #:ge
   #:gt
   #:compatible-with-a-term
   #:glb
   #:lub
   #:scheme-from-term
   #:schemes-from-terms
   #:term-from-scheme
   #:strictly-smaller-terms
   #:strictly-greater-terms
   #:prefixes-of-term
   #:prefixes-of-terms
   #:strict-prefixes-of-term
   #:strict-prefixes-of-terms
   #:extension
   #:nodes-satisfying-pred
   #:leaves-of-term
   #:term-depth
   #:term-size
   #:term-nb-leaves
   #:term-randomize-vbits
   #:compute-annotation
   #:erase-annotation
   #:remove-annotation
   #:run
   #:*show-run*
   #:toggle-show-run
   #:erase-run
   ))
